# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-dotnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install Required Tools
      run: dotnet tool restore
    - name: Build
      run: dotnet build --no-restore

    - name: Run the unit tests with code coverage
      run: dotnet coverage collect --output ${{ github.workspace }}/Tests/Coverage.cobertura.xml --output-format cobertura dotnet test --no-build --verbosity normal 

    - name: Generate Coverage Report
      run: dotnet reportgenerator -reports:${{ github.workspace }}/Tests/Coverage.cobertura.xml -targetdir:"${{ github.workspace }}/Tests/coveragereport" -reporttypes:MarkdownSummaryGithub -assemblyfilters:"-NUnit3.TestAdapter;-*.Tests;-Microsoft.*"

    - name: Publish Coverage Report
      run: cat "${{ github.workspace }}/Tests/coveragereport/SummaryGithub.md" >> $GITHUB_STEP_SUMMARY

